### ISSUE TITLE
Not installable with boss

### ISSUE THREAD

**Issue by TeoWin** [HashLoad/horse#283]
f:\Delphi 11\boss-windows-amd64\windows-amd64>boss install horse
[ERROR] boss.json not exists in f:\Delphi 11\boss-windows-amd64\windows-amd64

**Comment by viniciussanchez** [comment]
I understood.
You must learn to use Boss to install packages, or install packages manually.
To perform the installation manually, always download the sources from the latest released release.
![image](https://user-images.githubusercontent.com/16382981/220447124-ee772535-80c7-4378-8231-73cbea066526.png)
![image](https://user-images.githubusercontent.com/16382981/220447176-2b4b6c44-ba85-4daf-b697-0a8dd04f54cb.png)
Add in the library path or search path of the project, the src folder and be happy.
Note: the purpose of the boss is not similar to Delphi's GetIt. That's why he's not there.

**Comment by TeoWin** [comment]
Sorry but you did not understand what I try to explain. I just learned that Boss is some kind of package manager like npm. 
That is: the command prompt makes it look like a package manager.

Your description does not mention that you have to install Boss and how that can be done. It is not really common practice for a Delphi developer to use package managers. Normally one downloads a source zip file and compiles the runtime packages and then the designtime packages, adding the source folders to the library/browsing path of Delhi.
The only other way I know is Inno Setup.

**Comment by birbilis** [comment]
Can also try Boss Experts from GetIt for a GUI. It needs to have Boss installed first (and probably be able to find its executable on the system path)
