### ISSUE TITLE
Running on windows fails to load ssleay32.dll

### ISSUE THREAD

**Issue by WalRuS10** [HashLoad/horse#56]
I did not find any guide to make horse work in windows, the one I saw called "Horse: A revolução no REST" talks about compiling for linux. I think OpenSSL libraries are available in linux but i don't know how to get them correctly in windows.

**Comment by WalRuS10** [comment]
Another thing, I found an apparently unofficial installer "Win64OpenSSL_Light-1_1_1g" with that I ran the program. The only drawback I found was that when making a post it gives an access violation error in Horse.WebModule line 53: LResponse.Free; I solved it by commenting that line but I think it is not the correct way. I would like to know what I could do to solve that.

**Comment by CarlosHe** [comment]
You can download the dll's from the Indy website

**Comment by CarlosHe** [comment]
I think the error in line 53 is about reusing the same instance in request and response content. I'm not sure if this is going to be your situation. The request releases the content if it is a TObject type, the response will also release the same instance, but it will cause an error because the instance has already been released!
